'''
Created on Nov 22, 2010

@author: Peter
'''
from numpy import *
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.patches import Circle
import svmMLiA as sma
from mpl_toolkits.mplot3d import Axes3D

xcord0 = []
ycord0 = []
zcord0 = []
xcord1 = []
ycord1 = []
zcord1 = []
markers =[]
colors =[]
use_3d = False
fr = open('out.csv')#this file was generated by 2normalGen.py
for line in fr.readlines():
    lineSplit = line.strip().split(',')
    xPt = float(lineSplit[0])
    yPt = float(lineSplit[1])
    if(use_3d):
        zPt = float(lineSplit[2])
    label = int(lineSplit[4])
    if (label == -1):
        xcord0.append(xPt)
        ycord0.append(yPt)
        if(use_3d):
            zcord0.append(yPt)
    else:
        xcord1.append(xPt)
        ycord1.append(yPt)
        if(use_3d):
            zcord1.append(yPt)

fr.close()

#run smo algorithm
dataArr,labelArr = sma.loadDataSet('out.csv')
b,alphas = sma.smoP(dataArr, labelArr, 0.1, 0.15, 400)
ws= sma.calcWs(alphas,dataArr,labelArr)
print 'dataArr = ', dataArr
print 'alphas = ', alphas
print 'b = ', b 
print 'ws =', ws

fig = plt.figure()
#ax = Axes3D(fig)
#ax = fig.add_subplot(111,projection='3d')
ax = fig.add_subplot(111)
ax.scatter(xcord0,ycord0, marker='s', s=90)
ax.scatter(xcord1,ycord1,marker='o', s=50, c='red')
plt.title('Support Vectors Circled')
#circle = Circle((4.6581910000000004, 3.507396), 0.5, facecolor='none', edgecolor=(0,0.8,0.8), linewidth=3, alpha=0.5)
#ax.add_patch(circle)
#circle = Circle((3.4570959999999999, -0.082215999999999997), 0.5, facecolor='none', edgecolor=(0,0.8,0.8), linewidth=3, alpha=0.5)
#ax.add_patch(circle)
#circle = Circle((6.0805730000000002, 0.41888599999999998), 0.5, facecolor='none', edgecolor=(0,0.8,0.8), linewidth=3, alpha=0.5)
#ax.add_patch(circle)
#plt.plot([2.3,8.5], [-6,6]) #seperating hyperplane
#b = -3.75567; w0=0.8065; w1=-0.2761
w0=ws[0][0]; w1=ws[1][0];
if(use_3d):
    w2=ws[2][0]
x = arange(-1, 1, 0.1)
#y = arange(-1, 1, 0.1)
#x,y = meshgrid(x,y)
y = (-w0*x - b)/w1
#z = (-w0*x-w1*y - b)/w2
#z = [0.5 for i in range(len(x))]
ax.plot(x,y)
#ax.plot_surface(x, y, z,rstride=1, cstride=1, cmap='rainbow')
ax.axis([-1,1,-1,1])
plt.show()
